apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
commonAnnotations:
  environment: demo
commonLabels:
  environment: demo

resources:
  - resources/namespace.yaml
  - resources/pvc.yaml
  - resources/deployment.yaml