apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-claim
  labels:
    app: datastore
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: default
